### ISSUE TITLE
scannerEnabled property is not working

### ISSUE THREAD

**Issue by anilprime** [zxing-js/ngx-scanner#177]
**Describe the bug**
Even when the **EnableScanner** property is assigned as false, the camera scanner is able to scan the barcode, but as per my understanding the camera supposed to scan and decode the barcode only if the **EnableScanner** property is true.

**To Reproduce**
 <zxing-scanner #scanner3  [scannerEnabled]="scannerEnabled" [device]="currentDevice"  (scanSuccess)="handleQrCodeResult($event)"
            [formats]="['QR_CODE', 'EAN_13', 'CODE_128','ITF', 'DATA_MATRIX']" ></zxing-scanner>

**Screenshots**
N/A

**Desktop (please complete the following information):**
 -Window 10
 - Browser [chrome]
 - Version [64 bit]

**Comment by nCr78** [comment]
I solved this by calling `this.scanner.refreshCodeReader();` after setting `this.scanner.scannerEnabled` to `true/false` whenever I want to switch the camera/scanner on or off. However, this will turn off your camera completely until you set `scannerEnabled` back to `true` again. I don't think you can have the camera on and not scan at all. (Could be wrong, though, since I didn't need that behavior and didn't search for it)

**Comment by anilprime** [comment]
Thank you @nCr78 for the answer, but I don't want to switch off the camera, it must still remain in running condition and want to manage to handle the camera to scan the barcode or not by using scannerEnabled property.

**Comment by odahcam** [comment]
The `scannerEnabled`  is not something like a `ignoreScans` flag. It enables and disables the scanning system, entirely. This you expecting behavior is in development btw. If you want to so such thing you can just ignore successful scan results while handling whatever operation you need.
