### ISSUE TITLE
Use in Cordova App on iOS

### ISSUE THREAD

**Issue by wstrik** [zxing-js/ngx-scanner#271]
In relation to #167 and #210 I'm trying to get the zxing-js library working with Cordova on iOS.
Thanks to the related issues, it is working on Android. I guess it's the same problem that was with Android. Which is it doesn't has permissions for the camera.

I have just a blank page with the plugin on it. I get the following error:
`ERROR: {"line":2,"column":28352,"sourceURL":"..../zxing-umd.js"}`
Which reads:
`throw new Error("Can't enumerate devices, method not supported.");`
As said, i think this is because of no camera permissions.

I tried installing the barcodescanner with no result.

**Comment by odahcam** [comment]
Seems like camera permissions problem, have you tried using anything [like this](https://github.com/Cordobo/cordova-plugin-ios-camera-permissions)?

**Comment by wstrik** [comment]
Yes, I've installed that plugin also.

So I installed and started the Barcodescanner plugin. Than it asks for the camera permission and the plugin works. After that I loaded the zxing library, but still the same error.

Also when I run `navigator.mediaDevices.getUserMedia({ video: true })` it doesn't return anything.

**Comment by odahcam** [comment]
As [this comment](https://github.com/phonegap/phonegap-plugin-media-stream/issues/5#issuecomment-337404987) says, I think maybe cordova uses some web view implementation (obviously) and because of that the WebRTC API might not be available for Cordova on iOS. That seems like the same issue we have with PWAs at this moment.

**Comment by wstrik** [comment]
Hmm, thanks!

**Comment by odahcam** [comment]
Have you taken a look at React Native implementations?

**Comment by wstrik** [comment]
No. But I worked it out with the Cordova Barcodescanner plugin implemented in the hosted site. It only gets loaded when it's in the app. Otherswise it loads xzing.

**Comment by pj035** [comment]
We're having the same problem. It's a known limitation because of missing WebRTC support in the WkWebView (hopefully this changes soon). Anyhow, there is [cordova-plugin-iosrtc](https://www.npmjs.com/package/cordova-plugin-iosrtc), which provides an implementation of WebRTC. We tried that out and only succeeded partially. The camera loads and is visible, but the scanSuccess (nor error) event aren't triggered.

**Comment by uhotspot4** [comment]
@pj035 How could you use Cordova-plugin-iortc to get access to camera/mic? Because I still get the same error when in WKWebView! In my case I only need access to mic since my app is a voice chat.

**Comment by capc0** [comment]
@wstrik can you elaborate how you worked around this limitation and scan barcodes on iOS cordova?

**Comment by ninijay** [comment]
@pj035 Did you work out how to use it together with the cordova-plugin-iosrtc to trigger the scanSuccess event? Or did you solve it in another way. Would be interested as I'm facing similar issues and haven't tried it yet

**Comment by pj035** [comment]
@ninijay I was testing this for a customer app and due to time constraints I didn't follow it any further. We are now using one of the ionic plugins to scan QR codes. They are slower, but at least we can use them (no blame on ngx-scanner, but rather on Apple).

Sorry!

**Comment by odahcam** [comment]
Just as an update, latest iOS version seem to support the WebRTC API needed for this component to work. I didn't test it yet, but it's good news already.
