### ISSUE TITLE
Upgrade from 2.0.1 to 3.0.0 causes "ReferenceError: MediaDeviceInfo is not defined" in Internet Explorer 11

### ISSUE THREAD

**Issue by dtslvr** [zxing-js/ngx-scanner#294]
**Describe the bug**
We have upgraded from version `2.0.1` to `3.0.0 ` and now the app crashes and we're getting the following error in Internet Explorer 11: `ReferenceError: MediaDeviceInfo is not defined`.

Using `2.0.1` the app does not crash.

**To Reproduce**
1. Use `ngx-scanner` 3.0.0 within an Angular 9 app
2. Open the app in Internet Explorer 11
3. App crashes
4. See error: `ReferenceError: MediaDeviceInfo is not defined`

**Expected behavior**
The Angular app does not crash in Internet Explorer 11

**Desktop**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Comment by odahcam** [comment]
I'm not whiling to support IE. If anyone want to send a PR about this I'll accept. I believe this could be solved with a `MediaDeviceInfo` polyfill.

**Comment by dtslvr** [comment]
We do not need support for IE, it just should not crash. A polyfill for `MediaDeviceInfo` sounds like a reasonable solution. Unfortunately I could not find one ready to use in my web search.

**Comment by odahcam** [comment]
Making an exception in the code for not crashing in IE means supporting it in some way, I won't do that. If someone really think this should be added, PRs are still welcome.

**Comment by davidgg** [comment]
This is crashing to while testing with jest.

**Comment by odahcam** [comment]
As Jest runs tests in a Node environment, MediaDevice won't be available, because it comes from the browser.

**Comment by odahcam** [comment]
I'm not interested in supporting IE here. But PRs are still welcome. For Jest we may have to create extra checks inside the library to detect non-browser environments and alert the user without breaking the tests.

**Comment by Benjamin-Davies** [comment]
I am encountering this issue too when accessing an `ng serve` server from another host. Because the connection is not secure and it is not localhost, the browser is disabling the media apis. I am using *Chrome 83* on macOS Catalina. When I evaluate `MediaDeviceInfo` in the console on the dev site, it gives an error, as apposed to on a secure site such as GitHub where it returns a class.

It appears to be coming from what looks like auto-generated code from angular:

![Screen Shot 2020-07-03 at 10 01 40](https://user-images.githubusercontent.com/25046874/86412977-35ede480-bd14-11ea-80b3-eaf057ac34aa.png)

I have found a work-around, which is to set `window.MediaDeviceInfo` to an empty object if it is not defined, and I am running it before any of the modules are loaded.

```js
if (!window.MediaDeviceInfo) window.MediaDeviceInfo = {};
```

I am unsure why Angular has put `MediaDeviceInfo` directly into js when it was only in type definitions.

**Comment by odahcam** [comment]
@martea (a workaround)

![image](https://user-images.githubusercontent.com/3942006/90468601-418f4200-e0ed-11ea-8287-60359a0c9117.png)

**Comment by Shuyinsama** [comment]
This is a huge issue for me. Due to the nature of our application and the use of multi tenancy in our application we use our `hosts` file to locally test specific applications like for example:
`localhost:8081` = Main shop
`tenant1-dev:8081` = Tenant 1 shop

This is done since every tenant is the same shop but with their own style and settings and even products.
I can load the `localhost:8081` site perfectly fine and I can test it but whenever I browse too a tenants site it fully breaks. It does not even block only that specific function but makes the tenants local development completely unuseable.

The workaround does not seem to fix it for me since it can never find devices after that.

**Comment by odahcam** [comment]
@Shuyinsama it has nothing to do with this issue. The issue is because you need a secure server to access media device APIs outside localhost:

- https://github.com/zxing-js/ngx-scanner/issues/218#issuecomment-508536108
- https://github.com/zxing-js/ngx-scanner/issues/226#issuecomment-515202646
- https://github.com/zxing-js/ngx-scanner/issues/246#issuecomment-530516992
- https://github.com/zxing-js/ngx-scanner/issues/251#issuecomment-532772959
