### ISSUE TITLE
Gun Scanner

### ISSUE THREAD

**Issue by fra1979** [zxing-js/ngx-scanner#302]
Hi,
i'm trying to use it within my Angular2 Application.
Can you confirm if scanning a barcode with a Gun Scanner it will work, or if it works only with camera?

**Comment by odahcam** [comment]
Hello. Gun scanners are supposed to scan and decode the barcodes by itself and work as a keyboard input, nothing to with with this lib which handles buffer array decoding and a browser convinience layer for using cameras. So you should use both IF you wanna use a camera, otherwise you should use only the gun scanner.
