### ISSUE TITLE
Updated to new ngx-scanner 3.1.0 with error

### ISSUE THREAD

**Issue by mhosman** [zxing-js/ngx-scanner#355]
```
ERROR in The target entry-point "@zxing/ngx-scanner" has missing dependencies:
 - @zxing/browser
 - @zxing/library
```

Now we should install this packages manually?

**Comment by odahcam** [comment]
Yes.

**Comment by odahcam** [comment]
Long answer: it should be that way long ago, it just wasn't because the dependencies of the package were set wrong, this way (using peer dependencies instead of dependencies) users have more control over their own dependencies and can use the underlying packages directly if they want to, without conflicting or experiencing annoying behaviours. You can also benefit from patches from both packages where you couldn't before, having to wait until the next ngx-scanner release to get a patch already done, for example, in axing/library.

**Comment by KingDarBoja** [comment]
A update on readme should be made as pointed out by core maintainer but I would like to also point out that it should inform which one should be installed depending on the use case, I assume `@zxing/browser` is mostly needed for most end users for scanning and all that stuff whereas `@zxing/library` is the full API for any custom setup (not only browsers), right?

**Comment by odahcam** [comment]
#372 should solve this.

**Comment by fernandomeridamatilla** [comment]
Can you update your readme?

**Comment by odahcam** [comment]
Yeah, it needs to be rewritten. However I currently have no time for doing that.
