### ISSUE TITLE
Behaviour when camera is already opened

### ISSUE THREAD

**Issue by MrLegaropex** [zxing-js/ngx-scanner#371]
Let's assume this: I am developing a website which uses one specific camera for the zxing-scanner. Now if i open the same website in another tab/browser and try to access the same camera, which is already getting used, i get the following error:
![grafik](https://user-images.githubusercontent.com/76965818/103564019-18b1f280-4ebe-11eb-8d40-4457b2cefe3d.png)

Now this would be less of a problem if I could simply catch this error or handle it in another way. Unless I am missing something, in the last non-deprecated version (3.0.1) does not allow this, since none of the <zxing-scanner> - events return a value that can be used for this.

Google Chrome version: 87.0.4280.88
Mozilla Firefox version: 84.0.1
Angular version: 11.0.4
@zxing/library version: 0.18.3
@zxing/ngx-scanner version: 3.0.1

**Comment by odahcam** [comment]
I'm not sure if this is a **bug**. This will vary from browser to browser and is bit tricky to handle, that's why I never spent time on it. However, you have a few options to handle this issue: 

https://github.com/zxing-js/ngx-scanner/blob/42e6ad4f58fd235bd15d688d36050a4ea25fdc01/projects/zxing-scanner/src/lib/zxing-scanner.component.ts#L676-L739

Notice that this code snippet emits some values into some properties you can listen to. That console error message at least served it's purpose of letting you know this problem exists. 😌
