### ISSUE TITLE
Camera is rotated on iOS

### ISSUE THREAD

**Issue by LucaDaniele99** [zxing-js/ngx-scanner#509]
**Describe the bug**
When starting the QRCode scan, the video is rotated by 90° and there's no option in the ngx-scanner parameters to control this. 
On Android and browser (MacOS) is working correctly.

**Expected behavior**
Video in portrait mode, not landscape

**Screenshots**
![IMG_51744AD5CE00-1](https://user-images.githubusercontent.com/24780756/221350318-77d36677-401c-4fb9-b7c0-0bcae281fe49.jpeg)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.3
 - Browser: Safari, Chrome

**Comment by umeshsarkar** [comment]
We are facing the same issue, here is some additional information after testing on different devices. 

We tested on different devices, all with iOS version 16.3.1 and in Safari browser. 

The problem "camera rotated by 90 degrees" occurred when using the following devices:

- iPhone 12
- iPhone 14
- iPad 4

The problem did _not_ occur in the following devices (camera OK):

- iPhone SE
- iPhone X
- iPhone 11

One more observation on iPad 4: the problem did _not_ occur in the iOS version (16.2) but after updating the iOS version (16.3) the problem occurred.

**Comment by fabiomercorillo** [comment]
Hi,
the problem is related to the number of cameras detected and the selection of the default one. In particular, there are 4 cameras detected on the iPhone: front, rear, panoramic and wide angle (default); for this reason it is necessary to set the rear camera (index 1 in my case - iPhone 13) in the device list. Unfortunately there is no standard method that gives us the certainty of identifying the rear camera but we can rely on the description or on the index. You can use the "camerasFound" event of the component to get the list of cameras, while you can use the [device] attribute to set the desired camera. Here is a code snippet:

`<ng-container *ngFor="let c of camerasList">
        <ion-button (click)="onSelectCamera(c)">{{c.label}}</ion-button>
      </ng-container>

<zxing-scanner
      [enable]="selectedCamera !== undefined"
      (deviceChange)="onDeviceChange($event)"
      (camerasFound)="onCamerasFound($event)"
      [device]="selectedCamera"
      (scanError)="onScanError($event)"
      (scanFailure)="onScanFailure($event)"
      (scanSuccess)="onScanSuccess($event)"

      [formats]="allowedFormats"
      previewFitMode="cover"></zxing-scanner>`

`camerasList: Array<MediaDeviceInfo> = new Array<MediaDeviceInfo>();
  selectedCamera?: MediaDeviceInfo;

onCamerasFound($event: MediaDeviceInfo[]): void {
    this.camerasList = $event;
  }

onDeviceChange($event: MediaDeviceInfo): void {
    if (
      this.deviceInfo?.operatingSystem === 'ios' &&
      this.camerasList.length > 1
    ) {
      this.selectedCamera = this.camerasList[1];
    } else {
      this.selectedCamera = $event;
    }
  }`

I hope everything I've been doing is helpful.

Fabio

**Comment by Logic-Bits** [comment]
why is this closed? Problem is still here

**Comment by LucaDaniele99** [comment]
@Logic-Bits use solution provied by @fabiomercorillo, for me it resolved the problem. It's not a package problem as we need to select the camera to be opened or it will default to the first one in the list.
